### ISSUE TITLE
Remove unit scope names

### ISSUE THREAD

**Issue by jackdp** [Dennis1000/verysimplexml#8]
Please, remove unit scope names for compatibility with Delphi 2010 and XE.
Thank you for this library, I use it in several projects.

**Comment by Dennis1000** [comment]
Ah yes, the unit scope names. You should fork this library now, as the new 3.0 will be released in some days which will drop support for anything below Delphi 10.3.3
The reason is the removal of the workarounds for TStreamreader bugs in various Delphi versions etc, which slows down loading and parsing a lot. 
And I'm a fan of the new inline var feature which I'm using a lot in for-loops. 
The new version features a simple XPath SelectNode function too, but the current 2.0.5 does still a good job with any Delphi version below 10.3.
The current version 2.05 will be tagged as a Release version (haven't done yet), so you're able to download this even after I've published the v3.0.

**Comment by jackdp** [comment]
I use your library mainly in the XE7, so I forked ver. 2.05. Thanks for the information.

**Comment by jackdp** [comment]
I think we can close this issue. Thanks
